import listingPlaceholder from "@/assets/react.svg";
import type { Listing } from "./types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    tag: "rent",
    imageSrc: listingPlaceholder,
    priceRub: 1200,
    price: { kind: "per_day" },
    title: "Sony PlayStation 5 с 2 джойстиками",
    rating: 4.9,
    reviewsCount: 12,
    location: "Москва, м. Китай-город",
  },
  {
    id: "2",
    tag: "coownership",
    imageSrc: listingPlaceholder,
    priceRub: 15000,
    price: { kind: "share", percent: 10 },
    title: "Электросамокат Ninebot E2 Pro",
    rating: 5,
    reviewsCount: 4,
    location: "Доступно онлайн",
  },
  {
    id: "3",
    tag: "rent",
    imageSrc: listingPlaceholder,
    priceRub: 800,
    price: { kind: "per_day" },
    title: "Перфоратор Makita HR2470",
    rating: 4.8,
    reviewsCount: 35,
    location: "Москва, м. Выхино",
  },
  {
    id: "4",
    tag: "coownership",
    imageSrc: listingPlaceholder,
    priceRub: 2500,
    price: { kind: "share", percent: 25 },
    title: "Сапборд Gladiator Pro 10.6",
    rating: 4.7,
    reviewsCount: 2,
    location: "Пироговское вдхр.",
  },
  {
    id: "5",
    tag: "rent",
    imageSrc: listingPlaceholder,
    priceRub: 450,
    price: { kind: "per_day" },
    title: "Горный велосипед STELS Navigator 500 MD 26\"",
    rating: 4.6,
    reviewsCount: 8,
    location: "Москва, м. Сокол",
  },
  {
    id: "6",
    tag: "coownership",
    imageSrc: listingPlaceholder,
    priceRub: 3200,
    price: { kind: "share", percent: 15 },
    title: "Кофемашина De'Longhi Magnifica S",
    rating: 4.9,
    reviewsCount: 11,
    location: "Доступно онлайн",
  },
  {
    id: "7",
    tag: "rent",
    imageSrc: listingPlaceholder,
    priceRub: 2500,
    price: { kind: "per_day" },
    title: "Зеркальный фотоаппарат Canon EOS R50 + объектив",
    rating: 5,
    reviewsCount: 6,
    location: "Санкт-Петербург, м. Невский проспект",
  },
  {
    id: "8",
    tag: "coownership",
    imageSrc: listingPlaceholder,
    priceRub: 1800,
    price: { kind: "share", percent: 20 },
    title: "Палатка Trek Planet Denver 4",
    rating: 4.5,
    reviewsCount: 3,
    location: "Москва, Измайлово",
  },
];
