import {
  Baby,
  Box,
  Briefcase,
  Camera,
  Car,
  Gamepad2,
  Handshake,
  Home,
  Monitor,
  Music,
  PenTool,
  Plane,
  Smartphone,
  Star,
  Tent,
  Tv,
  Zap,
  Heart,
  MessageSquare,
  Search,
  User,
  Menu,
  MapPin,
  ChevronDown,
  ChevronRight,
  TrendingUp,
} from "lucide-react";
import listingPlaceholder from "@/assets/react.svg";
import type { Listing } from "@/types";

export const CATEGORIES = [
  { id: 1, name: "Электроника", icon: Smartphone },
  { id: 2, name: "Транспорт", icon: Plane },
  { id: 3, name: "Инструменты", icon: PenTool },
  { id: 4, name: "Спорт", icon: Zap },
  { id: 5, name: "Хобби", icon: Gamepad2 },
  { id: 6, name: "Техника", icon: Box },
  { id: 7, name: "Фото/Видео", icon: Camera },
  { id: 8, name: "Разное", icon: Star },
];

// ЗАМЕНЯТСЯ НА СЕРВЕРНЫЕ
export const CATALOG_CATEGORIES = [
  {
    id: "electro",
    name: "Электроника",
    icon: Smartphone,
    sub: [
      "Смартфоны",
      "Планшеты",
      "Ноутбуки",
      "Игровые приставки",
      "Наушники",
      "Умные часы",
    ],
  },
  {
    id: "photo",
    name: "Фото и видео",
    icon: Camera,
    sub: [
      "Фотоаппараты",
      "Объективы",
      "Видеокамеры",
      "Дроны",
      "Штативы",
      "Свет и студийное оборудование",
    ],
  },
  {
    id: "pc",
    name: "Компьютерная техника",
    icon: Monitor,
    sub: [
      "ПК",
      "Мониторы",
      "Проекторы",
      "Периферия",
      "VR-устройства",
      "Сетевое оборудование",
    ],
  },
  {
    id: "tools",
    name: "Инструменты и ремонт",
    icon: PenTool,
    sub: [
      "Дрели и шуруповерты",
      "Перфораторы",
      "Бензопилы",
      "Шлифмашины",
      "Строительные пылесосы",
      "Наборы инструментов",
    ],
  },
  {
    id: "home",
    name: "Дом и дача",
    icon: Home,
    sub: [
      "Газонокосилки",
      "Мойки высокого давления",
      "Садовый инструмент",
      "Лестницы и стремянки",
      "Генераторы",
      "Тепловое оборудование",
    ],
  },
  {
    id: "appliances",
    name: "Бытовая техника",
    icon: Tv,
    sub: [
      "Пылесосы",
      "Клининг-техника",
      "Кухонная техника",
      "Пароочистители",
      "Осушители и увлажнители",
      "Обогреватели",
    ],
  },
  {
    id: "transport",
    name: "Транспорт",
    icon: Car,
    sub: [
      "Велосипеды",
      "Электросамокаты",
      "Самокаты",
      "Детские кресла",
      "Багажники и боксы",
      "Автоаксессуары",
    ],
  },
  {
    id: "sport",
    name: "Спорт и отдых",
    icon: Tent,
    sub: [
      "Палатки",
      "Спальные мешки",
      "Сапборды",
      "Лыжи и сноуборды",
      "Туристическое снаряжение",
      "Велотренажеры",
    ],
  },
  {
    id: "hobby",
    name: "Хобби и развлечения",
    icon: Gamepad2,
    sub: [
      "Настольные игры",
      "Музыкальные инструменты",
      "Караоке и аудио",
      "Игровые наборы",
      "Проекторы для мероприятий",
      "Костюмы и реквизит",
    ],
  },
  {
    id: "events",
    name: "Для мероприятий",
    icon: Music,
    sub: [
      "Колонки",
      "Микрофоны",
      "Световое оборудование",
      "Декор",
      "Фотозоны",
      "Проекторы и экраны",
    ],
  },
  {
    id: "kids",
    name: "Детские товары",
    icon: Baby,
    sub: [
      "Коляски",
      "Автокресла",
      "Манежи",
      "Игрушки",
      "Электромобили",
      "Товары для праздников",
    ],
  },
  {
    id: "pro",
    name: "Профессиональное оборудование",
    icon: Briefcase,
    sub: [
      "Строительное оборудование",
      "Диагностические приборы",
      "Генераторы",
      "Измерительная техника",
      "Складское оборудование",
      "Оборудование для бизнеса",
    ],
  },
  {
    id: "coown",
    name: "Совладение",
    icon: Handshake,
    sub: [
      "Камеры и объективы",
      "Дроны",
      "Игровые приставки",
      "Электротранспорт",
      "Премиальная техника",
      "Инвестиционные проекты",
    ],
  },
  {
    id: "other",
    name: "Разное",
    icon: Box,
    sub: ["Редкие вещи", "Товары на сезон", "Новинки", "Локальные предложения"],
  },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    tag: "rent",
    imageSrc: listingPlaceholder,
    priceRub: 1200,
    price: { kind: "per_day" },
    title: "Sony PlayStation 5 с 2 джойстиками",
    rating: 4.9,
    reviewsCount: 12,
    location: "Москва, м. Китай-город",
  },
  {
    id: "2",
    tag: "coownership",
    imageSrc: listingPlaceholder,
    priceRub: 15000,
    price: { kind: "share", percent: 10 },
    title: "Электросамокат Ninebot E2 Pro",
    rating: 5,
    reviewsCount: 4,
    location: "Доступно онлайн",
  },
  {
    id: "3",
    tag: "rent",
    imageSrc: listingPlaceholder,
    priceRub: 800,
    price: { kind: "per_day" },
    title: "Перфоратор Makita HR2470",
    rating: 4.8,
    reviewsCount: 35,
    location: "Москва, м. Выхино",
  },
  {
    id: "4",
    tag: "coownership",
    imageSrc: listingPlaceholder,
    priceRub: 2500,
    price: { kind: "share", percent: 25 },
    title: "Сапборд Gladiator Pro 10.6",
    rating: 4.7,
    reviewsCount: 2,
    location: "Пироговское вдхр.",
  },
  {
    id: "5",
    tag: "rent",
    imageSrc: listingPlaceholder,
    priceRub: 450,
    price: { kind: "per_day" },
    title: 'Горный велосипед STELS Navigator 500 MD 26"',
    rating: 4.6,
    reviewsCount: 8,
    location: "Москва, м. Сокол",
  },
  {
    id: "6",
    tag: "coownership",
    imageSrc: listingPlaceholder,
    priceRub: 3200,
    price: { kind: "share", percent: 15 },
    title: "Кофемашина De'Longhi Magnifica S",
    rating: 4.9,
    reviewsCount: 11,
    location: "Доступно онлайн",
  },
  {
    id: "7",
    tag: "rent",
    imageSrc: listingPlaceholder,
    priceRub: 2500,
    price: { kind: "per_day" },
    title: "Зеркальный фотоаппарат Canon EOS R50 + объектив",
    rating: 5,
    reviewsCount: 6,
    location: "Санкт-Петербург, м. Невский проспект",
  },
  {
    id: "8",
    tag: "coownership",
    imageSrc: listingPlaceholder,
    priceRub: 1800,
    price: { kind: "share", percent: 20 },
    title: "Палатка Trek Planet Denver 4",
    rating: 4.5,
    reviewsCount: 3,
    location: "Москва, Измайлово",
  },
];
