/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `pickup` - pickup
* `mail` - mail
 */
export type DeliveryMethodEnum = typeof DeliveryMethodEnum[keyof typeof DeliveryMethodEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliveryMethodEnum = {
  pickup: 'pickup',
  mail: 'mail',
} as const;
