/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { Category } from './category';

export interface FavoriteCategory {
  readonly id: number;
  readonly category: Category;
  category_id: number;
  readonly created_at: string;
}
