/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ItemDetailOwner } from './itemDetailOwner';
import type { StatusFeaEnum } from './statusFeaEnum';
import type { ItemImage } from './itemImage';

export interface ItemDetail {
  readonly id: number;
  type: number;
  readonly type_name: string;
  readonly category_name: string;
  readonly owner: ItemDetailOwner;
  readonly owner_name: string;
  /** @maxLength 200 */
  name: string;
  description: string;
  characteristics?: unknown;
  status?: StatusFeaEnum;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  price: string;
  readonly images: readonly ItemImage[];
  readonly created_at: string;
  readonly updated_at: string;
}
