/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface ItemDetailOwner {
  readonly id: number;
  /** @maxLength 254 */
  email: string;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  /**
   * @maxLength 20
   * @pattern ^\+?1?\d{9,15}$
   */
  phone_number?: string;
  /** @nullable */
  profile_picture?: string | null;
  /** @maxLength 256 */
  country: string;
  /** @maxLength 256 */
  region: string;
  /** @maxLength 256 */
  city: string;
  /** @maxLength 256 */
  district: string;
  readonly rating: string;
  readonly reviews_count: string;
}
