/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `favorite_available` - Избранный предмет освободился
 */
export type KindEnum = typeof KindEnum[keyof typeof KindEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KindEnum = {
  favorite_available: 'favorite_available',
} as const;
