/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type ListingsItemMyListStatus = typeof ListingsItemMyListStatus[keyof typeof ListingsItemMyListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListingsItemMyListStatus = {
  available: 'available',
  maintenance: 'maintenance',
  rented: 'rented',
  unavailable: 'unavailable',
} as const;
