/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ListingsItemMyListStatus } from './listingsItemMyListStatus';

export type ListingsItemMyListParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * * `available` - Доступен
* `rented` - Сдан
* `maintenance` - На обслуживании
* `unavailable` - Недоступен
 */
status?: ListingsItemMyListStatus;
};
