/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ListingsItemListStatus } from './listingsItemListStatus';

export type ListingsItemListParams = {
category?: number;
created_at__gte?: string;
created_at__lte?: string;
max_price?: number;
min_price?: number;
owner?: number;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
search?: string;
/**
 * * `available` - Доступен
* `rented` - Сдан
* `maintenance` - На обслуживании
* `unavailable` - Недоступен
 */
status?: ListingsItemListStatus;
type?: number;
};
