/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { FavoriteCategory } from './favoriteCategory';

export interface PaginatedFavoriteCategoryList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: FavoriteCategory[];
}
