/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import { DeliveryMethodEnum } from './deliveryMethodEnum';
import { BlankEnum } from './blankEnum';

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchedItemDeliveryMethod = {...DeliveryMethodEnum,...BlankEnum,} as const