/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { KindEnum } from './kindEnum';

export interface PatchedNotification {
  readonly id?: number;
  readonly kind?: KindEnum;
  /** @nullable */
  readonly item?: number | null;
  readonly item_name?: string;
  readonly message?: string;
  is_read?: boolean;
  readonly created_at?: string;
}
