/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface PatchedCategory {
  readonly id?: number;
  /** @maxLength 100 */
  name?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
}
