/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface PatchedReview {
  readonly id?: number;
  readonly author?: number;
  readonly author_name?: string;
  readonly recipient?: number;
  readonly recipient_name?: string;
  transaction?: number;
  readonly item?: number;
  readonly item_name?: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating?: number;
  /** @nullable */
  comment?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
}
