/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface PatchedItemImage {
  readonly id?: number;
  item?: number;
  /** Изображение предмета */
  image?: string;
  /**
   * @maxLength 200
   * @nullable
   */
  alt_text?: string | null;
  is_main?: boolean;
  readonly created_at?: string;
}
