/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface PatchedSearchHistory {
  readonly id?: number;
  /** @maxLength 255 */
  query_text?: string;
  filters?: unknown;
  readonly created_at?: string;
  readonly last_searched_at?: string;
}
