/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ItemDetail } from './itemDetail';

export interface PatchedFavoriteItem {
  readonly id?: number;
  readonly item?: ItemDetail;
  item_id?: number;
  readonly created_at?: string;
}
