/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface PatchedItemType {
  readonly id?: number;
  category?: number;
  readonly category_name?: string;
  /** @maxLength 100 */
  name?: string;
  /** @nullable */
  usage_tips?: string | null;
  /** @nullable */
  safety_rules?: string | null;
  inspection_checklist?: unknown;
  characteristics_template?: unknown;
  readonly created_at?: string;
  readonly updated_at?: string;
}
