/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { StatusFeaEnum } from './statusFeaEnum';
import type { ProfileItemImage } from './profileItemImage';

export interface ProfileItem {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  price: string;
  status?: StatusFeaEnum;
  readonly updated_at: string;
  readonly image: ProfileItemImage;
}
