/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface ProfileItemImage {
  /**
   * URL изображения
   * @maxLength 200
   */
  url: string;
  /**
   * @maxLength 200
   * @nullable
   */
  alt_text?: string | null;
}
