/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { ProfileItem } from './profileItem';

export interface ProfilePage {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /**
   * @maxLength 20
   * @pattern ^\+?1?\d{9,15}$
   */
  phone_number?: string;
  readonly items: readonly ProfileItem[];
  /** @maxLength 256 */
  country: string;
  /** @maxLength 256 */
  region: string;
  /** @maxLength 256 */
  city: string;
  /** @maxLength 256 */
  district: string;
}
