/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { SchemaRetrieveFormat } from './schemaRetrieveFormat';
import type { SchemaRetrieveLang } from './schemaRetrieveLang';

export type SchemaRetrieveParams = {
format?: SchemaRetrieveFormat;
lang?: SchemaRetrieveLang;
};
