/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface SearchHistory {
  readonly id: number;
  query_text: string;
  filters?: unknown;
  readonly created_at: string;
}
