/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

/**
 * * `available` - Доступен
* `rented` - Сдан
* `maintenance` - На обслуживании
* `unavailable` - Недоступен
 */
export type StatusFeaEnum = typeof StatusFeaEnum[keyof typeof StatusFeaEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusFeaEnum = {
  available: 'available',
  rented: 'rented',
  maintenance: 'maintenance',
  unavailable: 'unavailable',
} as const;
