/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TransactionStatusEnum } from './transactionStatusEnum';

export interface Transaction {
  readonly id: number;
  readonly owner: number;
  readonly renter: number;
  readonly item: number;
  readonly rented_at: string;
  readonly status: TransactionStatusEnum;
  /** @nullable */
  readonly returned_at: string | null;
  readonly item_name: string;
  /** Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
  readonly renter_name: string;
  /** Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
  readonly owner_name: string;
  planned_start: string;
  planned_end: string;
}
