/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export type TransactionsListStatus = typeof TransactionsListStatus[keyof typeof TransactionsListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionsListStatus = {
  active: 'active',
  approved: 'approved',
  completed: 'completed',
  pending: 'pending',
  rejected: 'rejected',
  returning: 'returning',
} as const;
