/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import type { TransactionsListStatus } from './transactionsListStatus';

export type TransactionsListParams = {
item?: number;
owner?: number;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * * `pending` - pending
* `approved` - approved
* `rejected` - rejected
* `active` - active
* `returning` - returning
* `completed` - completed
 */
status?: TransactionsListStatus;
};
