/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */

export interface ViewHistory {
  readonly id: number;
  item: number;
  readonly item_name: string;
  readonly created_at: string;
}
